import assert from 'node:assert/strict';
import {buildReportFromMarkdown} from '../api/services/reportParser';
import {extractOpinions} from '../api/services/opinionExtractor';
import {buildReviewCandidate,buildReviewFieldGuards,reviewReportCandidate,validateReviewPatch} from '../api/services/researchReview';
import {projectReviewedReport} from '../api/services/reviewProjection';
import type {ReviewPatch} from '../api/domain/review';
const report=buildReportFromMarkdown({id:'ambiguity',filePath:'2026-09-16.md',markdown:'# 花旗\n\n广州发展（600098 CH，买入）。附录另列中性，评级有待确认。'});
const candidate=buildReviewCandidate(report,extractOpinions(report));
const statement=candidate.records.find(r=>r.kind==='statement')!;assert.equal(statement.kind,'statement');
const evidence=candidate.evidence.find(e=>e.quote.includes('买入')&&e.quote.includes('中性'))!;
const value=(rawLabel:string,normalizedLabel:'buy'|'neutral')=>({rawLabel,normalizedLabel,coverage:'rated',basis:'unknown',scaleRef:null,benchmarkText:null,horizonText:null});
const ambiguous={state:'ambiguous',value:null,evidenceIDs:[evidence.evidenceId],candidates:[{value:value('买入','buy'),evidenceIDs:[evidence.evidenceId]},{value:value('中性','neutral'),evidenceIDs:[evidence.evidenceId]}]};
const guard=buildReviewFieldGuards(statement).find(g=>g.path==='payload.rating')!;
const patch:ReviewPatch={baseRevisionId:candidate.reportRevisionId,baseCandidateHash:candidate.candidateHash,sourceHash:candidate.sourceHash,coverage:candidate.coverage,operations:candidate.reviewableRecordIDs.map(candidateId=>candidateId===statement.id?{op:'modify',candidateId,reason:'保留两种评级而不替原文选值',fieldChanges:[{path:guard.path,expectedValueHash:guard.expectedValueHash,value:ambiguous,evidenceIDs:[evidence.evidenceId]}]}:{op:'keep',candidateId,reason:'原文一致'}),issues:[]};
assert.equal(validateReviewPatch(patch,candidate).valid,true);
const bad=structuredClone(patch);bad.operations.find(o=>o.op==='modify')!.fieldChanges![0].value={...ambiguous,value:value('买入','buy')};assert.equal(validateReviewPatch(bad,candidate).valid,false,'ambiguous must not choose one value');
const result=await reviewReportCandidate(report,candidate,{providerId:'custom',providerName:'fixture',model:'fixture',apiKey:'fixture',baseUrl:'https://unused.invalid',timeoutMs:1000,dailyTokenBudget:100000,maxConcurrency:1},{provider:{test:async()=>{},async *stream(){},complete:async()=>({content:JSON.stringify(patch),finishReason:'stop',usage:{totalTokens:100}})}});
assert.equal(result.complete,true);assert.equal(result.readiness,'partial');assert.equal(projectReviewedReport(report,result).opinions[0].rating,null);assert(result.issues.some(i=>i.severity==='warning'));
console.log('ambiguous claims preserve alternatives without choosing a rating');
